-- spkg_init.lua — CLI entry, dispatches commands
-- Called from C as: spkg_main(cmd, home, args_table)

spkg_main = function(cmd, home, args)
    if cmd == "help" or cmd == "-h" or cmd == "--help" then
        print([[
spkg — Sharp Package Manager

  spkg init           create Sharp.lua
  spkg build          fetch deps + compile + link
  spkg run            build + run executable
  spkg add <name>     add a dependency
  spkg update         update all dependencies
  spkg clean          remove build/ and spkg_packages/
  spkg help           show this message
]])
        return true
    end

    if cmd == "init" then
        return spkg_cmd_init(home)
    end

    if not spkg.file_exists("Sharp.lua") then
        print("spkg: Sharp.lua not found. Run 'spkg init' first.")
        return false
    end

    local ok, manifest = pcall(dofile, "Sharp.lua")
    if not ok then
        print("spkg: failed to load Sharp.lua: " .. tostring(manifest))
        return false
    end

    if cmd == "build" then
        return spkg_cmd_build(manifest)
    elseif cmd == "run" then
        return spkg_cmd_run(manifest)
    elseif cmd == "add" then
        return spkg_cmd_add(manifest, args)
    elseif cmd == "update" then
        return spkg_cmd_update(manifest)
    elseif cmd == "clean" then
        return spkg_cmd_clean()
    else
        print("spkg: unknown command '" .. cmd .. "'. Try 'spkg help'.")
        return false
    end
end

-- ═══════════════════════════════════════════════════════════════
-- Lua table serializer (simple, for project manifests)
-- ═══════════════════════════════════════════════════════════════

function spkg_dump_lua(val, indent)
    indent = indent or 0
    local t = type(val)
    if t == "string" then return string.format("%q", val) end
    if t == "number" or t == "boolean" then return tostring(val) end
    if t == "nil" then return "nil" end
    if t == "table" then
        local pad = string.rep("  ", indent)
        -- Detect list-like array (all keys are positive integers contiguously)
        local max_k = 0
        local is_arr = true
        for k, _ in pairs(val) do
            if type(k) ~= "number" then is_arr = false; break end
            if k > max_k then max_k = k end
        end
        if is_arr and max_k > 0 then
            local parts = {}
            for i = 1, max_k do
                table.insert(parts, pad .. "  " .. spkg_dump_lua(val[i], indent + 1))
            end
            return "{\n" .. table.concat(parts, ",\n") .. "\n" .. pad .. "}"
        end
        -- String-keyed table
        local keys = {}
        for k, _ in pairs(val) do table.insert(keys, k) end
        table.sort(keys)
        local parts = {}
        for _, k in ipairs(keys) do
            table.insert(parts, pad .. "  " .. k .. " = " .. spkg_dump_lua(val[k], indent + 1))
        end
        return "{\n" .. table.concat(parts, ",\n") .. "\n" .. pad .. "}"
    end
    return "nil"
end

-- ═══════════════════════════════════════════════════════════════
-- Commands
-- ═══════════════════════════════════════════════════════════════

function spkg_cmd_init(home)
    if spkg.file_exists("Sharp.lua") then
        print("spkg: Sharp.lua already exists.")
        return false
    end
    local name = spkg.dir_exists("src") and "my-project" or "untitled"
    local src = [[
-- generated by spkg init
return {
  name = "%s",
  version = "0.1.0",
  type = "exe",
  src = { "src/**/*.sp" },
  deps = {},
  link = {}
}
]]
    spkg.write_file("Sharp.lua", string.format(src, name))
    print("spkg: created Sharp.lua")
    return true
end

function spkg_cmd_build(manifest)
    return spkg_build.execute(manifest)
end

function spkg_cmd_run(manifest)
    local ok = spkg_cmd_build(manifest)
    if not ok then return false end
    local name = manifest.name or "main"
    local exe = "build/" .. name
    if spkg.file_exists(exe) then
        local r = spkg.run_cmd("./" .. exe)
        print(r.out)
        return r.ok
    end
    print("spkg: executable not found: " .. exe)
    return false
end

function spkg_cmd_add(manifest, args)
    if #args < 1 then
        print("usage: spkg add <name>")
        return false
    end
    manifest.deps = manifest.deps or {}
    manifest.deps[args[1]] = "*"
    local out = "-- generated by spkg\nreturn " .. spkg_dump_lua(manifest)
    spkg.write_file("Sharp.lua", out)
    print("spkg: added dependency '" .. args[1] .. "'")
    return true
end

function spkg_cmd_update(manifest)
    print("spkg: update not yet implemented")
    return false
end

function spkg_cmd_clean()
    if spkg.dir_exists("build") then
        spkg.run_cmd("rm -rf build")
    end
    if spkg.dir_exists("spkg_packages") then
        spkg.run_cmd("rm -rf spkg_packages")
    end
    print("spkg: cleaned.")
    return true
end

return true