-- spkg_lock.lua — Sharp.lock read/write (Lua format)

local M = {}

function M.save(deps_info)
    local lock = {}
    for _, dep in ipairs(deps_info) do
        lock[dep.name] = {
            source = dep.url,
            version = dep.version,
            tag = dep.tag or "",
            commit = dep.commit or ""
        }
    end
    local out = "-- generated by spkg\nreturn " .. spkg_dump_lua(lock)
    spkg.write_file("Sharp.lock", out)
end

-- Save a single dep entry to Sharp.lock (update existing lock)
function M.save_one(dep)
    local lock = M.load() or {}
    lock[dep.name] = {
        source = dep.url,
        version = dep.version or "*",
        tag = dep.tag or "",
        commit = dep.commit or ""
    }
    local out = "-- generated by spkg\nreturn " .. spkg_dump_lua(lock)
    spkg.write_file("Sharp.lock", out)
end

function M.load()
    if not spkg.file_exists("Sharp.lock") then return nil end
    local ok, lock = pcall(dofile, "Sharp.lock")
    if not ok then return nil end
    return lock
end

return M
